apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: is-dey-apps-web
  namespace: dey-apps-docker2
  labels:
    app: app-dey-apps-web
spec:
  tags:
  - name: "latest"
    from:
      kind: DockerImage
      name: dey125r/dey-apps-web-openshift:v3
    referencePolicy:
      type: Source